### ISSUE TITLE
Tutorial for across samples analysis

### ISSUE THREAD

**Issue by Svanuytven** [shangll123/SpatialPCA_analysis_codes#1]
Dear developers,

Thank you for making such an amazing and an intuitive tool to use. I was wonder if you would also make a tutorial available for using your tool across multiple sections like mentioned in your manuscript.

Thank you very much in advance!

Sebastiaan

**Comment by shangll123** [comment]
Thank you for your interest in our method! I have updated the tutorial for multiple sample analysis here: https://lulushang.org/docs/Projects/SpatialPCA/DLPFC. I also made some improvements in the _SpatialPCA_Multiple_Sample_ function, so you may want to install the updated SpatialPCA to correctly run this function. 

Best,
Lulu
